### PR TITLE
[tmp] reverting changes in container cmdline

### PR DESCRIPTION
**Pull request by djarecka**
just to show that it works with the old cmdline

### CODE REVIEW

**Comment by satra** [comment]
the reason it works is that there are multiple things that have changed. just try master.

**Comment by djarecka** [comment]
@satra - I got this, you are right it wouldn't work in master. 
But right now I'm only saying that your modification to `cmdline` (both `Task` and `ContainerTask`) seem to not have any effect, so perhaps we can revert them.

**Comment by djarecka** [comment]
but if you really want to keep them, we can do it for now

**Comment by satra** [comment]
i think it was a bug, so i fixed it, and it should stay. the test i introduced would fail in master and pass in the current branch.

**Comment by djarecka** [comment]
but would pass without changes to `cmdline`...

**Comment by satra** [comment]
yes, but for other reasons.

**Pull request closed without merging**
